package instrument.stju.model.datamodel;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("calendar", "id", Calendar.class);
		arp.addMapping("class", "id", Class.class);
		arp.addMapping("classdetail", "id", Classdetail.class);
		arp.addMapping("classorder", "id", Classorder.class);
		arp.addMapping("classstudent", "id", Classstudent.class);
		arp.addMapping("classtimefeedback", "id", ClassTimeFeedback.class);
		arp.addMapping("fileurl", "id", Fileurl.class);
		arp.addMapping("helpcenter", "id", Helpcenter.class);
		arp.addMapping("insalbum", "id", InsAlbum.class);
		arp.addMapping("insattribute", "id", InsAttribute.class);
		arp.addMapping("insorder", "id", Insorder.class);
		arp.addMapping("inspic", "id", Inspic.class);
		arp.addMapping("instrument", "id", Instrument.class);
		arp.addMapping("orderins", "id", OrderIns.class);
		arp.addMapping("receiveraddress", "id", ReceiverAddress.class);
		arp.addMapping("slideshow", "id", SlideShow.class);
		arp.addMapping("suggestion", "id", Suggestion.class);
		arp.addMapping("teacher", "id", Teacher.class);
		arp.addMapping("userinfo", "id", Userinfo.class);
	}
}

