package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseCalendar;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Calendar extends BaseCalendar<Calendar> {
	public static final Calendar dao = new Calendar();
}
