package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseClass;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Class extends BaseClass<Class> {
	public static final Class dao = new Class();
}
