package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseClassorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classorder extends BaseClassorder<Classorder> {
	public static final Classorder dao = new Classorder();
}
