package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseClassTimeFeedback;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ClassTimeFeedback extends BaseClassTimeFeedback<ClassTimeFeedback> {
	public static final ClassTimeFeedback dao = new ClassTimeFeedback();
}
