package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseClassdetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classdetail extends BaseClassdetail<Classdetail> {
	public static final Classdetail dao = new Classdetail();
}
