package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseClassstudent;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Classstudent extends BaseClassstudent<Classstudent> {
	public static final Classstudent dao = new Classstudent();
}
