package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseFileurl;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Fileurl extends BaseFileurl<Fileurl> {
	public static final Fileurl dao = new Fileurl();
}
