package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseHelpcenter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Helpcenter extends BaseHelpcenter<Helpcenter> {
	public static final Helpcenter dao = new Helpcenter();
}
