package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseInsAttribute;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InsAttribute extends BaseInsAttribute<InsAttribute> {
	public static final InsAttribute dao = new InsAttribute();
}
