package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseInsAlbum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class InsAlbum extends BaseInsAlbum<InsAlbum> {
	public static final InsAlbum dao = new InsAlbum();
}
