package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseInsorder;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Insorder extends BaseInsorder<Insorder> {
	public static final Insorder dao = new Insorder();
}
