package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseInspic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Inspic extends BaseInspic<Inspic> {
	public static final Inspic dao = new Inspic();
}
