package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseInstrument;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Instrument extends BaseInstrument<Instrument> {
	public static final Instrument dao = new Instrument();
}
