package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseOrderIns;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OrderIns extends BaseOrderIns<OrderIns> {
	public static final OrderIns dao = new OrderIns();
}
