package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseReceiverAddress;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ReceiverAddress extends BaseReceiverAddress<ReceiverAddress> {
	public static final ReceiverAddress dao = new ReceiverAddress();
}
