package instrument.stju.model.datamodel;

/**
 * Created by Administrator on 2017/2/18.
 */

import instrument.stju.model.database.BaseSlideShow;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SlideShow extends BaseSlideShow<SlideShow> {
    public static final SlideShow dao = new SlideShow();
}

