package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseSuggestion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Suggestion extends BaseSuggestion<Suggestion> {
	public static final Suggestion dao = new Suggestion();
}
