package instrument.stju.model.datamodel;

import instrument.stju.model.database.BaseUserinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Userinfo extends BaseUserinfo<Userinfo> {
	public static final Userinfo dao = new Userinfo();
}
