package instrument.stju.model.database;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setTeacherId(java.lang.Integer teacherId) {
		set("teacherId", teacherId);
	}

	public java.lang.Integer getTeacherId() {
		return get("teacherId");
	}

	public void setTeacherName(java.lang.String teacherName) {
		set("teacherName", teacherName);
	}

	public java.lang.String getTeacherName() {
		return get("teacherName");
	}

	public void setTeacherTel(java.lang.String teacherTel) {
		set("teacherTel", teacherTel);
	}

	public java.lang.String getTeacherTel() {
		return get("teacherTel");
	}

	public void setStudentNum(java.lang.Integer studentNum) {
		set("studentNum", studentNum);
	}

	public java.lang.Integer getStudentNum() {
		return get("studentNum");
	}

	public void setClassId(java.lang.Integer classId) {
		set("classId", classId);
	}

	public java.lang.Integer getClassId() {
		return get("classId");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
