package instrument.stju.model.database;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClassTimeFeedback<M extends BaseClassTimeFeedback<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClassId(java.lang.Integer classId) {
		set("classId", classId);
	}

	public java.lang.Integer getClassId() {
		return get("classId");
	}

	public void setTimeId(java.lang.Integer timeId) {
		set("timeId", timeId);
	}

	public java.lang.Integer getTimeId() {
		return get("timeId");
	}

	public void setFeedback(java.lang.String feedback) {
		set("feedback", feedback);
	}

	public java.lang.String getFeedback() {
		return get("feedback");
	}

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setDate(java.lang.String date) {
		set("date", date);
	}

	public java.lang.String getDate() {
		return get("date");
	}

	public void setVideoUrl(java.lang.String videoUrl) {
		set("videoUrl", videoUrl);
	}

	public java.lang.String getVideoUrl() {
		return get("videoUrl");
	}
	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

}
