package instrument.stju.model.database;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInsorder<M extends BaseInsorder<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsrId(java.lang.Integer usrId) {
		set("usrId", usrId);
	}

	public java.lang.Integer getUsrId() {
		return get("usrId");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setTel(java.lang.String tel) {
		set("tel", tel);
	}

	public java.lang.String getTel() {
		return get("tel");
	}

	public void setMessage(java.lang.String message) {
		set("message", message);
	}

	public java.lang.String getMessage() {
		return get("message");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}

	public java.lang.Double getPrice() {
		return get("price");
	}

	public void setMethod(java.lang.String method) {
		set("method", method);
	}

	public java.lang.String getMethod() {
		return get("method");
	}

	public void setDate(java.lang.String date) {
		set("date", date);
	}

	public java.lang.String getDate() {
		return get("date");
	}

	public void setSituation(java.lang.String situation) {
		set("situation", situation);
	}

	public java.lang.String getSituation() {
		return get("situation");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setOrdernum(java.lang.Integer ordernum) {
		set("ordernum", ordernum);
	}

	public java.lang.Integer getOrdernum() {
		return get("ordernum");
	}

	public void setFreight(java.lang.Double freight) {
		set("freight", freight);
	}

	public java.lang.Double getFreight() {
		return get("freight");
	}

	public void setReveiverID(java.lang.Integer reveiverID) {
		set("reveiverID", reveiverID);
	}

	public java.lang.Integer getReveiverID() {
		return get("reveiverID");
	}

}
