package instrument.stju.model.database;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseInspic<M extends BaseInspic<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPicUrl(java.lang.String picUrl) {
		set("picUrl", picUrl);
	}

	public java.lang.String getPicUrl() {
		return get("picUrl");
	}

	public void setInsId(java.lang.Integer insId) {
		set("insId", insId);
	}

	public java.lang.Integer getInsId() {
		return get("insId");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
