package instrument.stju.model.database;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClass<M extends BaseClass<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClassName(java.lang.String className) {
		set("className", className);
	}

	public java.lang.String getClassName() {
		return get("className");
	}

	public void setClassPicUrl(java.lang.String classPicUrl) {
		set("classPicUrl", classPicUrl);
	}

	public java.lang.String getClassPicUrl() {
		return get("classPicUrl");
	}

	public void setLevel(java.lang.String level) {
		set("level", level);
	}

	public java.lang.String getLevel() {
		return get("level");
	}

	public void setLocal(java.lang.String local) {
		set("local", local);
	}

	public java.lang.String getLocal() {
		return get("local");
	}

	public void setAvailable(java.lang.String available) {
		set("available", available);
	}

	public java.lang.String getAvailable() {
		return get("available");
	}

	public void setClassPrice(java.lang.Integer classPrice) {
		set("classPrice", classPrice);
	}

	public java.lang.Integer getClassPrice() {
		return get("classPrice");
	}

	public void setClassNumber(java.lang.Integer classNumber) {
		set("classNumber", classNumber);
	}

	public java.lang.Integer getClassNumber() {
		return get("classNumber");
	}

	public void setClassTime(java.lang.Integer classTime) {
		set("classTime", classTime);
	}

	public java.lang.Integer getClassTime() {
		return get("classTime");
	}

	public void setClassRemark(java.lang.String classRemark) {
		set("classRemark", classRemark);
	}

	public java.lang.String getClassRemark() {
		return get("classRemark");
	}

	public void setFeedbackNum(java.lang.Integer feedbackNum) {
		set("feedbackNum", feedbackNum);
	}

	public java.lang.Integer getFeedbackNum() {
		return get("feedbackNum");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setTeacherName(java.lang.String teacherName) {
		set("teacherName", teacherName);
	}

	public java.lang.String getTeacherName() {
		return get("teacherName");
	}

}
