package instrument.stju.model.database;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserinfo<M extends BaseUserinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setLocation(java.lang.String location) {
		set("location", location);
	}

	public java.lang.String getLocation() {
		return get("location");
	}

	public void setIntrduction(java.lang.String intrduction) {
		set("intrduction", intrduction);
	}

	public java.lang.String getIntrduction() {
		return get("intrduction");
	}

	public void setOther(java.lang.String other) {
		set("other", other);
	}

	public java.lang.String getOther() {
		return get("other");
	}

	public void setHeadpic(java.lang.String headpic) {
		set("headpic", headpic);
	}

	public java.lang.String getHeadpic() {
		return get("headpic");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

}
